title: Eduardo Bouças
email: mail@eduardoboucas.com
description: Test
baseurl: ""
url: "https://eduardoboucas.com"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules

paginate: 6
paginate_path: "/page/:num/"

comments:
  url: "https://staticman.net/api/v1/entries/56bc6a83bad169944324e966"

googleAnalyticsId: UA-54012006-1  

gems:
  - jekyll-paginate

future: true