#########################
#						#
#   General settings	#
#						#
#########################
author: Eduardo Bouças
email: mail@eduardoboucas.com
feed_url: "http://feeds.eduardoboucas.com/eduardoboucas"
facebook_url: "https://www.facebook.com/eduardoboucas"
twitter_username: eduardoboucas
github_username:  eduardoboucas
googleAnalyticsId: UA-54012006-1

#########################
#						#
#  Main site settings	#
#						#
#########################
site_title: Eduardo Boucas
site_description: "A passionate and creative full-stack web developer that thinks code and numbers, but breathes art and design. Responsible and responsive. Terrible dancer."
site_url: "http://eduardoboucas.com"

#########################
#						#
#    Blog settings		#
#						#
#########################
blog_title: Eduardo saying things
blog_description: "My blog about web, my experience as a sharp programmer and a terrible dancer."
blog_url: "/blog"
markdown: kramdown

comment_post_url: http://pooleapp.com/stash/10de6ec7-27c4-469f-824a-8c0eee3ec105/

# Pagination
paginate: 5
paginate_path: "blog/page:num"

collections:
  - projects

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Eduardo Bouças"
      enable_comments: true  