# Site settings
title: Eduardo saying things
author: Eduardo Bouças
email: mail@eduardoboucas.com
description: "My blog about web, my experience as a sharp programmer and a terrible dancer."
baseurl: ""
url: "http://eduardoboucas.com"
blog_url: "/blog/"
feed_url: "http://feeds.eduardoboucas.com/eduardoboucas"
twitter_username: eduardoboucas
github_username:  eduardoboucas
googleAnalyticsId: UA-54012006-1

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "blog/page:num"

collections:
  - projects

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Eduardo Bouças"  