title: Eduardo Bouças
email: mail@eduardoboucas.com
description: "Software engineer with a crush on the web"
baseurl: ""
url: "https://eduardoboucas.com"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules

paginate: 6
paginate_path: "/page/:num/"

comments:
  url: "https://staticman.net/api/v1/entries/56bc6a83bad169944324e966"

googleAnalyticsId: UA-54012006-1  

gems:
  - jekyll-paginate

excerpt_separator: <!--more-->

future: true

# Serving
detach:  false
port:    4100
host:    0.0.0.0

# Staticman
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  akismet:
    enabled: true
    author: name
    content: message
  branch: master
  format: yml
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: md5
  url: http://localhost:8053/v1/entry/eduardoboucas/eduardoboucas.github.io/master
  #url: https://api.staticman.net/v1/entry/eduardoboucas/eduardoboucas.github.io/master